export declare const REGEX_DATE_YYYY_MM_DD: RegExp;
export declare const REGEX_DATE_ISO8601: RegExp;
export declare const YYYY_MM_DD = "y-MM-dd";
export declare const DATE_TIME = "y-MM-dd HH:mm:ss";
export declare const YYYY_MM_DD_T_TIME = "y-MM-dd'T'HH:mm:ss";
export declare const YYYY_MM_DD_TIME_OFFSET = "y-MM-dd HH:mm:ssZZ";
export declare const YYYY_MM_DD_TIME_MS_OFFSET = "y-MM-dd HH:mm:ss.SSSZZ";
export declare const YYYY_MM_DD_T_TIME_OFFSET = "y-MM-dd'T'HH:mm:ssZZ";
export declare const YYYY_MM_DD_T_TIME_MS_OFFSET = "y-MM-dd'T'HH:mm:ss.SSSZZ";
export declare const YYYY_MM_DD_T_TIME_Z = "y-MM-dd'T'HH:mm:ss'Z'";
export declare const UNIX_TIMESTAMP = "X";
export declare const FULL_YEAR = "y";
export declare const PREFIXED_MONTH = "MM";
export declare const PREFIXED_DAY = "dd";
export declare const USA_MM_DD_YYYY_DATE = "MM/dd/yy";
export declare const USA_MM_DD_YYYY_DATE_TIME = "MM/dd/yy HH:mm:ss";
export declare type DateRange = {
    startDate: Date;
    endDate: Date;
};
