"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Wrappers = exports.JWT = exports.OAuthAuthenticator = exports.JWTBearerAuthAuthenticator = exports.BearerAuthAuthenticator = exports.BasicAuthAuthenticator = exports.createJWTSecurity = exports.createOAuthSecurity = exports.createBearerSecurity = exports.createBasicSecurity = void 0;
const tslib_1 = require("tslib");
var create_security_1 = require("../support/create-security");
Object.defineProperty(exports, "createBasicSecurity", { enumerable: true, get: function () { return create_security_1.createBasicSecurity; } });
Object.defineProperty(exports, "createBearerSecurity", { enumerable: true, get: function () { return create_security_1.createBearerSecurity; } });
Object.defineProperty(exports, "createOAuthSecurity", { enumerable: true, get: function () { return create_security_1.createOAuthSecurity; } });
Object.defineProperty(exports, "createJWTSecurity", { enumerable: true, get: function () { return create_security_1.createJWTSecurity; } });
var basic_auth_authenticator_1 = require("./basic-auth-authenticator");
Object.defineProperty(exports, "BasicAuthAuthenticator", { enumerable: true, get: function () { return (0, tslib_1.__importDefault)(basic_auth_authenticator_1).default; } });
var bearer_auth_authenticator_1 = require("./bearer-auth-authenticator");
Object.defineProperty(exports, "BearerAuthAuthenticator", { enumerable: true, get: function () { return (0, tslib_1.__importDefault)(bearer_auth_authenticator_1).default; } });
var jwt_bearer_auth_authenticator_1 = require("./jwt-bearer-auth-authenticator");
Object.defineProperty(exports, "JWTBearerAuthAuthenticator", { enumerable: true, get: function () { return (0, tslib_1.__importDefault)(jwt_bearer_auth_authenticator_1).default; } });
var oauth_authenticator_1 = require("./oauth-authenticator");
Object.defineProperty(exports, "OAuthAuthenticator", { enumerable: true, get: function () { return (0, tslib_1.__importDefault)(oauth_authenticator_1).default; } });
exports.JWT = (0, tslib_1.__importStar)(require("./jwt"));
exports.Wrappers = (0, tslib_1.__importStar)(require("./wrappers"));
