"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Wrappers = exports.JWT = exports.QueryStringAuthenticator = exports.PreauthUriTokenAuthenticator = exports.OauthRefreshAuthenticator = exports.PrefetchTokenAuthorizationHeaderAuthenticator = exports.CustomHeaderAuthenticator = exports.NonBearerAuthorizationAuthenticator = exports.OAuthAuthenticator = exports.JWTBearerAuthAuthenticator = exports.BearerAuthAuthenticator = exports.BasicAuthAuthenticator = exports.createQueryStringSecurity = exports.createSimpleAuthorizationHeaderSecurity = exports.createQueryParamterPrefetchTokenSecurity = exports.createPrefetchTokenAuthorizationHeadersSecurity = exports.createOAuthRefreshSecurity = exports.createCustomHeadersSecurity = exports.createCustomHeaderSecurity = exports.createJWTSecurity = exports.createOAuthSecurity = exports.createBearerSecurity = exports.createBasicSecurity = void 0;
const tslib_1 = require("tslib");
var create_security_1 = require("../support/create-security");
Object.defineProperty(exports, "createBasicSecurity", { enumerable: true, get: function () { return create_security_1.createBasicSecurity; } });
Object.defineProperty(exports, "createBearerSecurity", { enumerable: true, get: function () { return create_security_1.createBearerSecurity; } });
Object.defineProperty(exports, "createOAuthSecurity", { enumerable: true, get: function () { return create_security_1.createOAuthSecurity; } });
Object.defineProperty(exports, "createJWTSecurity", { enumerable: true, get: function () { return create_security_1.createJWTSecurity; } });
Object.defineProperty(exports, "createCustomHeaderSecurity", { enumerable: true, get: function () { return create_security_1.createCustomHeaderSecurity; } });
Object.defineProperty(exports, "createCustomHeadersSecurity", { enumerable: true, get: function () { return create_security_1.createCustomHeadersSecurity; } });
Object.defineProperty(exports, "createOAuthRefreshSecurity", { enumerable: true, get: function () { return create_security_1.createOAuthRefreshSecurity; } });
Object.defineProperty(exports, "createPrefetchTokenAuthorizationHeadersSecurity", { enumerable: true, get: function () { return create_security_1.createPrefetchTokenAuthorizationHeadersSecurity; } });
Object.defineProperty(exports, "createQueryParamterPrefetchTokenSecurity", { enumerable: true, get: function () { return create_security_1.createQueryParamterPrefetchTokenSecurity; } });
Object.defineProperty(exports, "createSimpleAuthorizationHeaderSecurity", { enumerable: true, get: function () { return create_security_1.createSimpleAuthorizationHeaderSecurity; } });
Object.defineProperty(exports, "createQueryStringSecurity", { enumerable: true, get: function () { return create_security_1.createQueryStringSecurity; } });
var basic_auth_authenticator_1 = require("./basic-auth-authenticator");
Object.defineProperty(exports, "BasicAuthAuthenticator", { enumerable: true, get: function () { return tslib_1.__importDefault(basic_auth_authenticator_1).default; } });
var bearer_auth_authenticator_1 = require("./bearer-auth-authenticator");
Object.defineProperty(exports, "BearerAuthAuthenticator", { enumerable: true, get: function () { return tslib_1.__importDefault(bearer_auth_authenticator_1).default; } });
var jwt_bearer_auth_authenticator_1 = require("./jwt-bearer-auth-authenticator");
Object.defineProperty(exports, "JWTBearerAuthAuthenticator", { enumerable: true, get: function () { return tslib_1.__importDefault(jwt_bearer_auth_authenticator_1).default; } });
var oauth_authenticator_1 = require("./oauth-authenticator");
Object.defineProperty(exports, "OAuthAuthenticator", { enumerable: true, get: function () { return tslib_1.__importDefault(oauth_authenticator_1).default; } });
// Additional authenticators
var non_bearer_authorization_authenticator_1 = require("./non-bearer-authorization-authenticator");
Object.defineProperty(exports, "NonBearerAuthorizationAuthenticator", { enumerable: true, get: function () { return tslib_1.__importDefault(non_bearer_authorization_authenticator_1).default; } });
var custom_header_authenticator_1 = require("./custom-header-authenticator");
Object.defineProperty(exports, "CustomHeaderAuthenticator", { enumerable: true, get: function () { return tslib_1.__importDefault(custom_header_authenticator_1).default; } });
var prefetch_token_authorization_header_authenticator_1 = require("./prefetch-token-authorization-header-authenticator");
Object.defineProperty(exports, "PrefetchTokenAuthorizationHeaderAuthenticator", { enumerable: true, get: function () { return tslib_1.__importDefault(prefetch_token_authorization_header_authenticator_1).default; } });
var oauth_refresh_authenticator_1 = require("./oauth-refresh-authenticator");
Object.defineProperty(exports, "OauthRefreshAuthenticator", { enumerable: true, get: function () { return tslib_1.__importDefault(oauth_refresh_authenticator_1).default; } });
var preauth_uri_token_authenticator_1 = require("./preauth-uri-token-authenticator");
Object.defineProperty(exports, "PreauthUriTokenAuthenticator", { enumerable: true, get: function () { return tslib_1.__importDefault(preauth_uri_token_authenticator_1).default; } });
var query_string_authenticator_1 = require("./query-string-authenticator");
Object.defineProperty(exports, "QueryStringAuthenticator", { enumerable: true, get: function () { return tslib_1.__importDefault(query_string_authenticator_1).default; } });
exports.JWT = tslib_1.__importStar(require("./jwt"));
exports.Wrappers = tslib_1.__importStar(require("./wrappers"));
